Add on method to request object
Since there was no on method and the following error occurred
```
TypeError: request.on is not a function
```

Reference:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html